behaviors:
  AI_Demo:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 128
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
      gail:
        strength: 0.4
        gamma: 0.99
        demo_path: demo/F90Demo_13.demo
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
    behavioral_cloning:
      strength: 0.5
      demo_path: demo/F90Demo_13.demo
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true